import { Expression as SharedExpression } from "@/shared/types/expression";

export const INITIAL_EXPRESSION: SharedExpression = {
  id: "initial",
  text: "is packed with",
  translation: "está lleno de / está repleto de",
  meaning: "To be completely full of something or someone.",
  metadata: {
    secondaryMeanings: ["crammed with", "crowded with", "brimming with"],
    type: "phrasal verb / collocation",
    cefr: "B2",
    ipa: "/ɪz pækt wɪð/",
    frequency: 0.75,
    formality: "Neutral / Informal",
    mnemonic: "Imagine two gears that 'fit together' perfectly to work without noise.",
    imageUrl: "/Users/mauroociappina/.gemini/antigravity/brain/3681305e-92dc-4eaf-b866-34ecea1b4aed/get_along_visual_1778506922743.png",
  },
  linguistics: {
    usageTips: {
      context: "Used to describe places, events, or objects that are at full capacity.",
      naturalness: "Very natural in both spoken and written English.",
      commonMistake: "Students often forget the 'with' or the 'ed' (e.g., 'is pack with').",
    },
    tenses: {
      present_simple: { text: "The stadium is packed with fans.", translation: "El estadio está repleto de fans." },
      past_simple: { text: "The stadium was packed with people last night.", translation: "El estadio estaba lleno de gente anoche." },
      future_simple: { text: "The stadium will be packed with supporters tomorrow.", translation: "El estadio estará lleno de seguidores mañana." },
      present_continuous: { text: "The stadium is being packed with fans for the event.", translation: "El estadio se está llenando de fans para el evento." },
      past_continuous: { text: "The stadium was being packed with fans when it started to rain.", translation: "El estadio se estaba llenando de fans cuando empezó a llover." },
      future_continuous: { text: "The stadium will be being packed with fans at 8 PM.", translation: "El estadio se estará llenando de fans a las 8 PM." },
      present_perfect: { text: "The stadium has been packed with fans all afternoon.", translation: "El estadio ha estado lleno de fans toda la tarde." },
      past_perfect: { text: "The stadium had been packed with fans before the game was cancelled.", translation: "El estadio había estado lleno de fans antes de que el juego se cancelara." },
      future_perfect: { text: "The stadium will have been packed with fans by the time you arrive.", translation: "El estadio habrá estado lleno de fans para cuando llegues." },
      present_perfect_continuous: { text: "The stadium has been being packed with fans for hours.", translation: "El estadio se ha estado llenando de fans por horas." },
      past_perfect_continuous: { text: "The stadium had been being packed with fans before the gates closed.", translation: "El estadio se había estado llenando de fans antes de que cerraran las puertas." },
      future_perfect_continuous: { text: "The stadium will have been being packed with fans for three hours by then.", translation: "El estadio se habrá estado llenando de fans por tres horas para ese entonces." },
      present_passive: { text: "The venue is packed with equipment by the crew.", translation: "El lugar es llenado con equipos por el equipo de trabajo." },
      past_passive: { text: "The stadium was packed with people by the organizers.", translation: "El estadio fue llenado con gente por los organizadores." },
      future_passive: { text: "The stadium will be packed with fans by the marketing team.", translation: "El estadio será llenado con fans por el equipo de marketing." },
      present_perfect_passive: { text: "The venue has been packed with equipment.", translation: "El lugar ha sido llenado con equipos." },
      past_perfect_passive: { text: "The venue had been packed with equipment before the show.", translation: "El lugar había sido llenado con equipos antes del show." },
      future_perfect_passive: { text: "The venue will have been packed with equipment by noon.", translation: "El lugar habrá sido llenado con equipos para el mediodía." },
      conditional_0: { text: "If a place is packed with people, it's usually noisy.", translation: "Si un lugar está lleno de gente, usualmente es ruidoso." },
      conditional_1: { text: "If you arrive late, the stadium will be packed with fans.", translation: "Si llegas tarde, el estadio estará lleno de fans." },
      conditional_2: { text: "If the concert were free, the stadium would be packed with fans.", translation: "Si el concierto fuera gratis, el estadio estaría lleno de fans." },
      conditional_3: { text: "If they had promoted it more, the stadium would have been packed with fans.", translation: "Si lo hubieran promocionado más, el estadio habría estado lleno de fans." },
      conditional_mixed: { text: "If I hadn't lost my ticket, I would be in that stadium packed with fans now.", translation: "Si no hubiera perdido mi entrada, ahora estaría en ese estadio lleno de fans." },
      modal_can: { text: "The stadium can be packed with fans during the finals.", translation: "El estadio puede estar lleno de fans durante las finales." },
      modal_could: { text: "The stadium could be packed with fans if we don't limit capacity.", translation: "El estadio podría estar lleno de fans si no limitamos la capacidad." },
      modal_should: { text: "The stadium should be packed with fans for such a big event.", translation: "El estadio debería estar lleno de fans para un evento tan grande." },
      modal_must: { text: "The stadium must be packed with fans; I hear a lot of noise.", translation: "El estadio debe estar lleno de fans; escucho mucho ruido." },
      modal_might: { text: "The stadium might be packed with fans, so arrive early.", translation: "El estadio podría estar lleno de fans, así que llega temprano." },
      modal_may: { text: "The stadium may be packed with fans later today.", translation: "El estadio puede que esté lleno de fans más tarde hoy." },
      modal_would: { text: "The stadium would be packed with fans anyway.", translation: "El estadio estaría lleno de fans de todas formas." },
      used_to: { text: "The stadium used to be packed with fans every weekend.", translation: "El estadio solía estar lleno de fans cada fin de semana." },
      reported_speech: { text: "He said that the stadium was packed with fans.", translation: "Él dijo que el estadio estaba lleno de fans." },
      subjunctive: { text: "It is essential that the stadium be packed with fans for the finals.", translation: "Es esencial que el estadio esté lleno de fans para las finales." },
      imperative: { text: "Make sure the stadium is packed with fans!", translation: "¡Asegúrate de que el estadio esté lleno de fans!" },
      gerund_form: { text: "Being packed with fans makes the stadium look alive.", translation: "Estar lleno de fans hace que el estadio se vea vivo." },
      infinitive_form: { text: "It's common to be packed with fans during the summer.", translation: "Es común estar lleno de fans durante el verano." },
      question_form: { text: "Is the stadium packed with fans already?", translation: "¿Ya está el estadio lleno de fans?" },
      negative_form: { text: "The stadium isn't packed with fans today.", translation: "El estadio no está lleno de fans hoy." },
      relative_clause: { text: "The stadium, which is packed with fans, is amazing.", translation: "El estadio, que está lleno de fans, es increíble." },
      phrasal_structure: { text: "They packed it with fans until there was no space.", translation: "Lo llenaron de fans hasta que no quedó espacio." },
    },
    wordFamilies: {
      noun: ["pack", "package", "packaging", "packet"],
      verb: ["pack", "repack", "unpack"],
      adjective: ["packed", "packing"],
      adverb: []
    },
    phrasalVerbDetails: {
      verb: "is",
      particle: "packed with",
      separable: "no",
      transitive: true,
      commonCollocations: ["is packed with fans", "is packed with information", "is packed with flavor"]
    },
    examples: [
      {
        category: "Medical Drama",
        text: "The emergency room is packed with flu patients tonight, stat!",
        translation: "La sala de emergencias está llena de pacientes con gripe esta noche, ¡rápido!",
        literalTranslation: "La sala de emergencias está empacada con gripe pacientes esta noche, estadístico!",
        subtitleAdaptation: "¡Urgencias está colapsada de pacientes con gripe, muévanse!",
        tone: "Urgent, commanding",
        register: "Medical Slang / Fast-paced",
        explanation: "Typical high-stress hospital scene."
      },
      {
        category: "Courtroom Thriller",
        text: "Your honor, the gallery is packed with the victim's family.",
        translation: "Su señoría, la galería está repleta de la familia de la víctima.",
        literalTranslation: "Su honor, la galería está empacada con la víctima familia.",
        subtitleAdaptation: "Su señoría, la sala está llena de familiares de la víctima.",
        tone: "Serious, formal tension",
        register: "Highly Formal / Legal",
        explanation: "Used to set a tense mood in a legal drama."
      },
      {
        category: "90s Sitcom",
        text: "Can't go in there, man. The fridge is packed with Joey's weird sandwiches.",
        translation: "No podés entrar ahí, viejo. La heladera está llena de los sándwiches raros de Joey.",
        literalTranslation: "No puedo ir en ahí, hombre. El refrigerador está empacado con de Joey raros sándwiches.",
        subtitleAdaptation: "Ni entres. La heladera está a tope con los sándwiches raros de Joey.",
        tone: "Casual, comedic warning",
        register: "Street Casual / Slang",
        explanation: "Classic sitcom exaggeration of an everyday problem."
      }
    ]
  },
  study: {
    status: 'pending',
    difficulty: 1,
    timesStudied: 0,
    interval: 0,
    easiness: 2.5,
  },
  createdAt: new Date().toISOString(),
  updatedAt: new Date().toISOString(),
};
